### ISSUE TITLE
a plugin that reminds of things archived as done?

### ISSUE THREAD

**Issue by dhfromkorea** [ginatrapani/todo.txt-cli#145]
I have been thinking it would be great if I could be reminded of the things I had done for each day. For example, by receiving a daily digest email or a growl-like notification on a desktop. 

I am curious if there's already a plugin that does a similar thing? If not, I would like to work on it so that it can integrate with services like idonethis.com? 

Any pointers would be deeply appreciated.

**Comment by dumblob** [comment]
Use *cron(5)* (or similar) and check the saved dates.

**Comment by dumblob** [comment]
Actually, nearly all the work is done - https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#lately-report-of-recently-completed-tasks .

**Comment by dhfromkorea** [comment]
Thanks. Let me try out the add-on. If it does not work out, I will fall back on the cron job.
