### ISSUE TITLE
hide tasks

### ISSUE THREAD

**Issue by schiesbn** [ginatrapani/todo.txt-cli#158]
I use todo.txt together with Simpletask on my Android phone. On Simpletask I can create hiddden tasks, e.g. to define all my common projects and contexts so that they are also available if there is no task assigned. That's really useful because it allows you to always auto-complete projects and contexts, even if you just create the first task for it. Simpletask defines this hidden tasks by adding "h:1" to the task description. Is it possible to also hide this tasks from todo.txt-cli?

I would be also willing to write my own extension for it, if you give me some pointer how this could be done.

**Comment by ginatrapani** [comment]
Sounds like a great idea for an extension! Wanna give it a shot? The mailing list is the best place for extension development support.

**Comment by schiesbn** [comment]
Was easier than I thought :smile: 
Here is the extension in case it us useful for someone else too: https://github.com/schiesbn/todotxt/blob/master/todo.actions.d/hide
