### ISSUE TITLE
ImportError: No module named gflags

### ISSUE THREAD

**Issue by johannesjo** [ginatrapani/todo.txt-cli#161]
I installed the google tasks extension by following the instructions provided in its readme. The google-python-api, as well as the oauth package is successfully installed. It still shows this error, when I try to run `todo.sh google ...`

**Comment by amcintosh** [comment]
I've removed the references to gflags from the code, as it wasn't in use. 
If you grab the latest, it should be good to go.

I've also rewritten the README and cleaned the code up a bit. Haven't touched this in years so I'm thinking of spending some time cleaning it up a lot.

Thanks

**Comment by johannesjo** [comment]
Thanks for trying to fix this issue. Unfortunately now I get another error:
```
Pulling from Google Tasks
Traceback (most recent call last):
  File "/home/johannes/.todo.actions.d/google", line 282, in <module>
    main(sys.argv[1:])
  File "/home/johannes/.todo.actions.d/google", line 269, in main
    pull()
  File "/home/johannes/.todo.actions.d/google", line 149, in pull
    service = getAPIService()
  File "/home/johannes/.todo.actions.d/google", line 85, in getAPIService
    credentials = run(FLOW, storage)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/tools.py", line 247, in run
    'The gflags library must be installed to use tools.run(). '
NotImplementedError: The gflags library must be installed to use tools.run(). Please install gflags or preferrably switch to using tools.run_flow().
```

**Comment by johannesjo** [comment]
I was able to fix this issue by running:
```
pip install python-gflags
```

**Comment by amcintosh** [comment]
ok. Glad it's working for you. I've further updated the instructions.
